name: Deploy to DigitalOcean

on:
  push:
    branches: [master]

jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./back-end

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: JWT_SECRET=testsecret npx mocha test/**/*.test.js
        
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy files to droplet via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/root/app"

    - name: SSH into droplet and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/app
          docker-compose down
          docker-compose up -d --build